export interface Country {
  name: string;
  code: string;
  dial: string;
}

export const countries: Country[] = [
  { name: "Argentina", code: "ar", dial: "54" },
  { name: "Uruguay", code: "uy", dial: "598" },
  { name: "Paraguay", code: "py", dial: "595" },
  { name: "Chile", code: "cl", dial: "56" },
  { name: "Brasil", code: "br", dial: "55" },
  { name: "Bolivia", code: "bo", dial: "591" },
  { name: "Colombia", code: "co", dial: "57" },
  { name: "Perú", code: "pe", dial: "51" },
  { name: "Ecuador", code: "ec", dial: "593" },
  { name: "Venezuela", code: "ve", dial: "58" },
  { name: "México", code: "mx", dial: "52" },
  { name: "España", code: "es", dial: "34" },
  { name: "Estados Unidos", code: "us", dial: "1" },
  { name: "Canadá", code: "ca", dial: "1" },
  { name: "Reino Unido", code: "gb", dial: "44" },
  { name: "Alemania", code: "de", dial: "49" },
  { name: "Francia", code: "fr", dial: "33" },
  { name: "Italia", code: "it", dial: "39" },
  { name: "Portugal", code: "pt", dial: "351" },
  { name: "Suiza", code: "ch", dial: "41" },
  { name: "Países Bajos", code: "nl", dial: "31" },
  { name: "Bélgica", code: "be", dial: "32" },
  { name: "Costa Rica", code: "cr", dial: "506" },
  { name: "Panamá", code: "pa", dial: "507" },
  { name: "República Dominicana", code: "do", dial: "1" },
  { name: "Puerto Rico", code: "pr", dial: "1" },
  { name: "Guatemala", code: "gt", dial: "502" },
  { name: "El Salvador", code: "sv", dial: "503" },
  { name: "Honduras", code: "hn", dial: "504" },
  { name: "Nicaragua", code: "ni", dial: "505" },
  { name: "Cuba", code: "cu", dial: "53" },
  { name: "China", code: "cn", dial: "86" },
  { name: "Japón", code: "jp", dial: "81" },
  { name: "Australia", code: "au", dial: "61" },
  { name: "Nueva Zelanda", code: "nz", dial: "64" },
  { name: "Sudáfrica", code: "za", dial: "27" },
  { name: "Rusia", code: "ru", dial: "7" },
  { name: "India", code: "in", dial: "91" },
  { name: "Corea del Sur", code: "kr", dial: "82" },
  { name: "Singapur", code: "sg", dial: "65" },
  { name: "Andorra", code: "ad", dial: "376" },
  { name: "Afganistán", code: "af", dial: "93" },
  { name: "Albania", code: "al", dial: "355" },
  { name: "Argelia", code: "dz", dial: "213" },
  { name: "Angola", code: "ao", dial: "244" },
  { name: "Arabia Saudita", code: "sa", dial: "966" },
  { name: "Armenia", code: "am", dial: "374" },
  { name: "Austria", code: "at", dial: "43" },
  { name: "Azerbaiyán", code: "az", dial: "994" },
  { name: "Bahamas", code: "bs", dial: "1" },
  { name: "Bahréin", code: "bh", dial: "973" },
  { name: "Bangladesh", code: "bd", dial: "880" },
  { name: "Barbados", code: "bb", dial: "1" },
  { name: "Bielorrusia", code: "by", dial: "375" },
  { name: "Belice", code: "bz", dial: "501" },
  { name: "Benín", code: "bj", dial: "229" },
  { name: "Bermudas", code: "bm", dial: "1" },
  { name: "Bután", code: "bt", dial: "975" },
  { name: "Bosnia y Herzegovina", code: "ba", dial: "387" },
  { name: "Botsuana", code: "bw", dial: "267" },
  { name: "Brunéi", code: "bn", dial: "673" },
  { name: "Bulgaria", code: "bg", dial: "359" },
  { name: "Burkina Faso", code: "bf", dial: "226" },
  { name: "Burundi", code: "bi", dial: "257" },
  { name: "Cabo Verde", code: "cv", dial: "238" },
  { name: "Camboya", code: "kh", dial: "855" },
  { name: "Camerún", code: "cm", dial: "237" },
  { name: "República Centroafricana", code: "cf", dial: "236" },
  { name: "Chad", code: "td", dial: "235" },
  { name: "Chipre", code: "cy", dial: "357" },
  { name: "República del Congo", code: "cg", dial: "242" },
  { name: "República Democrática del Congo", code: "cd", dial: "243" },
  { name: "Croacia", code: "hr", dial: "385" },
  { name: "Dinamarca", code: "dk", dial: "45" },
  { name: "Yibuti", code: "dj", dial: "253" },
  { name: "Dominica", code: "dm", dial: "1" },
  { name: "Egipto", code: "eg", dial: "20" },
  { name: "Emiratos Árabes Unidos", code: "ae", dial: "971" },
  { name: "Eritrea", code: "er", dial: "291" },
  { name: "Eslovaquia", code: "sk", dial: "421" },
  { name: "Eslovenia", code: "si", dial: "386" },
  { name: "Estonia", code: "ee", dial: "372" },
  { name: "Etiopía", code: "et", dial: "251" },
  { name: "Fiyi", code: "fj", dial: "679" },
  { name: "Finlandia", code: "fi", dial: "358" },
  { name: "Gabón", code: "ga", dial: "241" },
  { name: "Gambia", code: "gm", dial: "220" },
  { name: "Georgia", code: "ge", dial: "995" },
  { name: "Ghana", code: "gh", dial: "233" },
  { name: "Gibraltar", code: "gi", dial: "350" },
  { name: "Grecia", code: "gr", dial: "30" },
  { name: "Groenlandia", code: "gl", dial: "299" },
  { name: "Guam", code: "gu", dial: "1" },
  { name: "Guinea", code: "gn", dial: "224" },
  { name: "Guinea-Bisáu", code: "gw", dial: "245" },
  { name: "Guinea Ecuatorial", code: "gq", dial: "240" },
  { name: "Guyana", code: "gy", dial: "592" },
  { name: "Haití", code: "ht", dial: "509" },
  { name: "Hong Kong", code: "hk", dial: "852" },
  { name: "Hungría", code: "hu", dial: "36" },
  { name: "Islandia", code: "is", dial: "354" },
  { name: "Indonesia", code: "id", dial: "62" },
  { name: "Irán", code: "ir", dial: "98" },
  { name: "Irak", code: "iq", dial: "964" },
  { name: "Irlanda", code: "ie", dial: "353" },
  { name: "Israel", code: "il", dial: "972" },
  { name: "Jamaica", code: "jm", dial: "1" },
  { name: "Jordania", code: "jo", dial: "962" },
  { name: "Kazajistán", code: "kz", dial: "7" },
  { name: "Kenia", code: "ke", dial: "254" },
  { name: "Kirguistán", code: "kg", dial: "996" },
  { name: "Kiribati", code: "ki", dial: "686" },
  { name: "Kuwait", code: "kw", dial: "965" },
  { name: "Laos", code: "la", dial: "856" },
  { name: "Letonia", code: "lv", dial: "371" },
  { name: "Líbano", code: "lb", dial: "961" },
  { name: "Lesoto", code: "ls", dial: "266" },
  { name: "Liberia", code: "lr", dial: "231" },
  { name: "Libia", code: "ly", dial: "218" },
  { name: "Liechtenstein", code: "li", dial: "423" },
  { name: "Lituania", code: "lt", dial: "370" },
  { name: "Luxemburgo", code: "lu", dial: "352" },
  { name: "Macao", code: "mo", dial: "853" },
  { name: "Macedonia del Norte", code: "mk", dial: "389" },
  { name: "Madagascar", code: "mg", dial: "261" },
  { name: "Malaui", code: "mw", dial: "265" },
  { name: "Malasia", code: "my", dial: "60" },
  { name: "Maldivas", code: "mv", dial: "960" },
  { name: "Malí", code: "ml", dial: "223" },
  { name: "Malta", code: "mt", dial: "356" },
  { name: "Islas Marshall", code: "mh", dial: "692" },
  { name: "Mauritania", code: "mr", dial: "222" },
  { name: "Mauricio", code: "mu", dial: "230" },
  { name: "Micronesia", code: "fm", dial: "691" },
  { name: "Moldavia", code: "md", dial: "373" },
  { name: "Mónaco", code: "mc", dial: "377" },
  { name: "Mongolia", code: "mn", dial: "976" },
  { name: "Montenegro", code: "me", dial: "382" },
  { name: "Marruecos", code: "ma", dial: "212" },
  { name: "Mozambique", code: "mz", dial: "258" },
  { name: "Birmania (Myanmar)", code: "mm", dial: "95" },
  { name: "Namibia", code: "na", dial: "264" },
  { name: "Nauru", code: "nr", dial: "674" },
  { name: "Nepal", code: "np", dial: "977" },
  { name: "Nueva Caledonia", code: "nc", dial: "687" },
  { name: "Níger", code: "ne", dial: "227" },
  { name: "Nigeria", code: "ng", dial: "234" },
  { name: "Noruega", code: "no", dial: "47" },
  { name: "Omán", code: "om", dial: "968" },
  { name: "Pakistán", code: "pk", dial: "92" },
  { name: "Palaos", code: "pw", dial: "680" },
  { name: "Palestina", code: "ps", dial: "970" },
  { name: "Papúa Nueva Guinea", code: "pg", dial: "675" },
  { name: "Filipinas", code: "ph", dial: "63" },
  { name: "Polonia", code: "pl", dial: "48" },
  { name: "Polinesia Francesa", code: "pf", dial: "689" },
  { name: "Catar", code: "qa", dial: "974" },
  { name: "Rumania", code: "ro", dial: "40" },
  { name: "Ruanda", code: "rw", dial: "250" },
  { name: "Samoa", code: "ws", dial: "685" },
  { name: "San Marino", code: "sm", dial: "378" },
  { name: "Senegal", code: "sn", dial: "221" },
  { name: "Serbia", code: "rs", dial: "381" },
  { name: "Seychelles", code: "sc", dial: "248" },
  { name: "Sierra Leona", code: "sl", dial: "232" },
  { name: "Islas Salomón", code: "sb", dial: "677" },
  { name: "Somalia", code: "so", dial: "252" },
  { name: "Sri Lanka", code: "lk", dial: "94" },
  { name: "Sudán", code: "sd", dial: "249" },
  { name: "Surinam", code: "sr", dial: "597" },
  { name: "Suecia", code: "se", dial: "46" },
  { name: "Siria", code: "sy", dial: "963" },
  { name: "Taiwán", code: "tw", dial: "886" },
  { name: "Tayikistán", code: "tj", dial: "992" },
  { name: "Tanzania", code: "tz", dial: "255" },
  { name: "Tailandia", code: "th", dial: "66" },
  { name: "Togo", code: "tg", dial: "228" },
  { name: "Tonga", code: "to", dial: "676" },
  { name: "Trinidad y Tobago", code: "tt", dial: "1" },
  { name: "Túnez", code: "tn", dial: "216" },
  { name: "Turquía", code: "tr", dial: "90" },
  { name: "Turkmenistán", code: "tm", dial: "993" },
  { name: "Tuvalu", code: "tv", dial: "688" },
  { name: "Uganda", code: "ug", dial: "256" },
  { name: "Ucrania", code: "ua", dial: "380" },
  { name: "Uzbekistán", code: "uz", dial: "998" },
  { name: "Vanuatu", code: "vu", dial: "678" },
  { name: "Vietnam", code: "vn", dial: "84" },
  { name: "Yemen", code: "ye", dial: "967" },
  { name: "Zambia", code: "zm", dial: "260" },
  { name: "Zimbabue", code: "zw", dial: "263" }
];
