/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,sgn,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#c8c6c5",
        "tertiary-fixed-dim": "#e9c176",
        "on-primary-fixed-variant": "#474746",
        "outline-variant": "#c4c7c7",
        "on-surface-variant": "#444748",
        "outline": "#747878",
        "on-secondary": "#ffffff",
        "slate-blue": "#4A5568",
        "primary-fixed": "#e5e2e1",
        "surface-bright": "#f8f9fa",
        "background": "#f8f9fa",
        "primary": "#000000",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#111c2c",
        "error": "#ba1a1a",
        "surface-dim": "#d9dadb",
        "primary-container": "#1c1b1b",
        "on-secondary-container": "#586377",
        "tertiary-container": "#261900",
        "inverse-on-surface": "#f0f1f2",
        "secondary-fixed-dim": "#bcc7dd",
        "on-primary-container": "#858383",
        "surface-container-high": "#e7e8e9",
        "deep-charcoal": "#121212",
        "on-surface": "#191c1d",
        "tertiary-fixed": "#ffdea5",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-tint": "#5f5e5e",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#5d4201",
        "secondary": "#545f72",
        "surface-container-highest": "#e1e3e4",
        "inverse-surface": "#2e3132",
        "on-background": "#191c1d",
        "error-container": "#ffdad6",
        "surface-container-low": "#f3f4f5",
        "tertiary": "#000000",
        "surface": "#f8f9fa",
        "surface-container": "#edeeef",
        "on-tertiary-fixed": "#261900",
        "pure-white": "#FFFFFF",
        "off-white": "#F7F8F9",
        "on-tertiary-container": "#a17f3b",
        "secondary-fixed": "#d8e3fa",
        "secondary-container": "#d5e0f7",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#1c1b1b",
        "inverse-primary": "#c8c6c5",
        "surface-variant": "#e1e3e4"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
      },
      spacing: {
        "margin-desktop": "64px",
        "container-max": "1440px",
        "section-gap": "120px",
        "gutter": "32px",
        "base": "8px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "sans": ["Montserrat", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "label-sm": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "label-lg": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "headline-xl": ["40px", { "lineHeight": "48px", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "500" }],
        "headline-lg": ["30px", { "lineHeight": "38px", "fontWeight": "600" }],
        "body-md": ["15px", { "lineHeight": "22px", "fontWeight": "300" }],
        "display-lg-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "display-lg": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-lg": ["13px", { "lineHeight": "18px", "letterSpacing": "0.06em", "fontWeight": "600" }],
        "body-lg": ["17px", { "lineHeight": "26px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
